### ISSUE TITLE
GeometryCollections might or might not be features

### ISSUE THREAD

**Issue by tcql** [Turfjs/turf-geometrycollection#1]
I've typically used geometrycollections like featurecollections; not wrapped as features: 

``` js
{
   "type": "GeometryCollection",
   "geometries": [
     // ...
   ]
}
```

I don't see there often being use-cases for a geometrycollection wrapped in a feature.

**Comment by tmcw** [comment]
I've seen both usages; we should stay consistent with the other geometry types.
